
meta_product_name: "SMAP"
meta_title: "SMAP - Ma solution mobilité à budget contrôlé"
meta_description: "Votre budget automobile devient simple et transparent. Véhicule, assurance, essence, entretien: Smap s’occupe de tout et vous ne profitez que du plaisir de rouler et de la liberté de vous déplacer, sans aucune contraintes."
meta_image: "ogimage.jpg"
twitter_account: "@Smap_mobility"
